POST http://localhost:8889/api/quizzes/1/solve
Content-Type: application/json

{
  "answer": [1, 2, 5]
}

###
POST http://localhost:8889/api/quizzes/4/solve
Content-Type: application/json

{
  "answer": [1, 3]
}

###
POST http://localhost:8889/api/quizzes/4/solve
Content-Type: application/json

{
  "answer": []
}

###
